### PR TITLE
Make the Glob independent on the location of the .editorconfig file it was loaded from

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@angelozerr could you please review?

2490114 is there to de-couple the `Glob` class from the path of `.editorconfig` file it was loaded from. I find this design is cleaner, a bit easier to test and the `Glob` class becomes a bit better re-usable.

1c84965 simply makes the two tests known to fail on Windows ignored. I created #79 and #80 to track those two failing tests so that we do not forget to eventually re-enable them when possible.

**Comment by angelozerr** [comment]
Is ec4e needs a PR?

**Comment by ppalaga** [comment]
> Is ec4e needs a PR?

I did not think of it. Let me have a look.

**Comment by ppalaga** [comment]
The ec4e PR https://github.com/angelozerr/ec4e/pull/37

**Comment by angelozerr** [comment]
Ok thanks @ppalaga for your answer and your PR!

**Pull request merged**
