### PR TITLE
Give access to the undelying java.nio.file.Path of the Ec4jPath

### PR DESCRIPTION
**Pull request by ppalaga**
fix https://github.com/ec4j/ec4j/issues/127

@Vampire is this enough for your needs?

### CODE REVIEW

**Comment by Vampire** [comment]
Well, not really.
It is much better with it thanks, as in my work-around I could use the actual `Path` instead of relying on `Ec4jPath#toString`.
But I would still need this 20 lines work-around I showed in the other ticket when it would be much nicer to just get the list from ec4j. :-)

**Comment by ppalaga** [comment]
How about c7a4108

**Comment by Vampire** [comment]
That looks very promising, thank you very much. :-)

**Comment by ppalaga** [comment]
Could you please build locally, try and confirm that it works for you, before I release 1.0.0?

**Comment by Vampire** [comment]
Unwillingly, I try to avoid touching Maven with a five-foot pole if I can avoid it. :-D

Yeah, works fine, with the PR branch it is the much cleaner
```kotlin
val relevantFiles = ResourcePropertiesService
    .builder()
    .build()
    .queryProperties(Resources.ofPath(destinationDirectory.asFile.absoluteFile.toPath(), UTF_8))
    .editorConfigFiles
    .map { it.getAdapter(Path::class.java) }
```
Thank you for your fast and thorough action. :-)

**Comment by ppalaga** [comment]
I have released 1.0.0

**Comment by Vampire** [comment]
Yes, thanks, already integrated :-) https://github.com/karakum-team/karakum/pull/34/files#diff-72ddbab765d336775f430538e1c2fa35c79742083e09b0befcece9b1d4448044R93-R99

**Pull request merged**
